version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::015658449406:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-28bgoYzABuD1"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::015658449406:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-i8KVwhokj6HD"
cloudformation_execution_role = "arn:aws:iam::015658449406:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-uDvW9EeCuwrX"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1n5unyu6kwl95"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::015658449406:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-q8hZuEANFErF"
cloudformation_execution_role = "arn:aws:iam::015658449406:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-gTHRYrDzUMqq"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-kf70loxkim3m"
image_repository = ""
region = "us-east-1"
